language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO_VERSION=1.4.8
  - DJANGO_VERSION=1.5.4
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION=1.4.8
    - python: "3.3"
      env: DJANGO_VERSION=1.4.8
install:
  - pip install Django==$DJANGO_VERSION
script: python setup.py test
